version: "2"

services:
    db:
        image: mongo
        container_name: "mongodb"
        
        ports:
            - "27018:27017"
    web:
        build: .
        command: flask run
        ports:
            - "5000:5000"
        depends_on: 
            - db

        network_mode: "host"